// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'firebase_options.dart';

// ...


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHxjeRz0EHGt7AC0xbdQDhK9hAW8WqUHY',
    appId: '1:892377282506:web:c3bfea793fba7a980f8133',
    messagingSenderId: '892377282506',
    projectId: 'fir-app-1-fbc9f',
    authDomain: 'fir-app-1-fbc9f.firebaseapp.com',
    storageBucket: 'fir-app-1-fbc9f.appspot.com',
    measurementId: 'G-LG4LDHK4MQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXzrx4JdkB-suAZeqIwxj4BBI50pMUdlU',
    appId: '1:892377282506:android:2127501c51977d700f8133',
    messagingSenderId: '892377282506',
    projectId: 'fir-app-1-fbc9f',
    storageBucket: 'fir-app-1-fbc9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfMg3YUcvDtGBRLXX8TcIm1rWmTL9fvCU',
    appId: '1:892377282506:ios:3af9fb768fc34f6e0f8133',
    messagingSenderId: '892377282506',
    projectId: 'fir-app-1-fbc9f',
    storageBucket: 'fir-app-1-fbc9f.appspot.com',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfMg3YUcvDtGBRLXX8TcIm1rWmTL9fvCU',
    appId: '1:892377282506:ios:fb33f88e2a1ba3aa0f8133',
    messagingSenderId: '892377282506',
    projectId: 'fir-app-1-fbc9f',
    storageBucket: 'fir-app-1-fbc9f.appspot.com',
    iosBundleId: 'com.example.demoApp.RunnerTests',
  );
}
